version: '3.9'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: meta
      POSTGRES_PASSWORD: meta
      POSTGRES_DB: meta_dj
    ports: [ "5432:5432" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U meta -d meta_dj" ]
      interval: 5s
      timeout: 3s
      retries: 10

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: meta
      MINIO_ROOT_PASSWORD: meta12345
    command: server /data --console-address ":9001"
    ports: [ "9000:9000", "9001:9001" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: ./services/api-go
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://meta:meta@db:5432/meta_dj?sslmode=disable
      STORAGE_ENDPOINT: http://minio:9000
      STORAGE_BUCKET: meta-dj
      STORAGE_ACCESS_KEY_ID: meta
      STORAGE_SECRET_ACCESS_KEY: meta12345
    ports: [ "8080:8080" ]
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports: [ "3001:3001" ]
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8080
    depends_on:
      - api
