services:
  api:
    build:
      context: ./services/api-go
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:postgres@host.docker.internal:54322/postgres?sslmode=disable}
      SUPABASE_URL: ${SUPABASE_URL:-http://host.docker.internal:54321}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY:-}
      SUPABASE_STORAGE_BUCKET: ${SUPABASE_STORAGE_BUCKET:-meta-dj}
      SUPABASE_JWKS_URL: ${SUPABASE_JWKS_URL:-http://host.docker.internal:54321/auth/v1/keys}
      IMPORT_HOST_PREFIX: ${IMPORT_HOST_PREFIX:-}
      IMPORT_CONTAINER_PREFIX: ${IMPORT_CONTAINER_PREFIX:-/import}
    ports: [ "8080:8080" ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${IMPORT_HOST_ROOT:-/mnt/c/Users/pasca/Music}:/import:ro

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    ports: [ "3001:3001" ]
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-http://api:8080}
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL:-}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY:-}
    depends_on:
      - api
