services:
  api:
    build:
      context: ./services/api-go
      dockerfile: Dockerfile
    env_file:
      - .env
    ports: [ "8080:8080" ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${IMPORT_HOST_ROOT:-/mnt/c/Users/pasca/Music}:/import:ro

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports: [ "3001:3001" ]
    env_file:
      - .env
    depends_on:
      - api
