[package]
name = "meta-dj-analyzer-rs"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
symphonia = { version = "0.5", features = ["aac", "flac", "isomp4", "mp3", "vorbis", "wav"] }
sha1_smol = "1"
hex = "0.4"


